<?php

namespace App\Api\Request\DB\Chat;


use App\Api\Request\PaginatedRequest;
use App\Message;
use App\User;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Illuminate\Validation\Validator;

class ConversationsRequest extends PaginatedRequest
{

    /** @var Guard */
    protected $guard;

    /**
     * ConversationsRequest constructor.
     * @param Guard $guard
     */
    public function __construct(Guard $guard)
    {
        $this->guard = $guard;
    }

    /**
     * @inheritDoc
     */
    protected function shouldResolve()
    {
        return true;//$this->guard->check();
    }

    /**
     * @inheritDoc
     */
    protected function rules(Validator $validator = null)
    {
        return [];
    }

    /**
     * @inheritdoc
     */
    protected function urlParameters(Collection $parameters)
    {
        return [];
    }

    /**
     * @inheritdoc
     */
    protected function paginator(Collection $parameters, $perPage, $page)
    {
        /** @var User $user */
        $user = $this->guard->user();

        $result = Message::conversationsWith(1)->get();

        return new LengthAwarePaginator($result->forPage($page, $perPage), $result->count(), $perPage, $page);
    }

    /**
     * @inheritDoc
     */
    protected function resourceClass()
    {
        return parent::resourceClass(); // TODO: Change the autogenerated stub
    }
}